### ISSUE TITLE
Invalid module "Foundryvtt-digitable-initiative-led" detected in directory "foundryvtt-digitable-initiative-led"

### ISSUE THREAD

**Issue by MrSergeantF** [mcules/FoundryVTT-digitable-initiative-led#1]
There is an issue with the "module.json" in v1.0.1:

The ID String seems to have to be in lower case only. With the upper case letters as it is, I get the Error "Invalid Module" (as in the title). After changing it to lower case letters and restarting Foundry the Module was useable.

**Comment by mcules** [comment]
Thank you for reporting the error. I have fixed it in the current version.
The updater should work from the next release onwards. Unfortunately, this update will still need to be installed manually.
